name: Publish Snapshot package

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  publish:
    uses: jeanpierrefortune/keypop.keypop-actions/.github/workflows/reusable-publish-snapshot.yml@publish-snapshot-v1
