name: 'Publish Java API documentation'
on:
  push:
    branches:
      - main
      - 'release-*'
  workflow_dispatch:

jobs:
  publish-doc:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set scripts permissions
        run: chmod +x scripts/*.sh

      - name: Extract version
        id: version
        run: |
          VERSION=$(grep version gradle.properties | cut -d= -f2 | tr -d "[:space:]")
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          # Determine if this is a release commit
          if [[ "${{ github.event.head_commit.message }}" == "Release $VERSION" ]]; then
            echo "is_snapshot=false" >> "$GITHUB_OUTPUT"
          else
            echo "is_snapshot=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Generate Javadoc
        run: ./gradlew javadoc

      - name: Prepare documentation
        run: |
          chmod +x ./scripts/prepare_javadoc.sh
          ./scripts/prepare_javadoc.sh ${{ github.event.repository.name }} ${{ steps.version.outputs.version }} ${{ steps.version.outputs.is_snapshot }}

      - name: Commit and push documentation
        working-directory: ${{ github.event.repository.name }}
        run: |
          git config user.email "${{ github.event.repository.name }}-bot@eclipse.org"
          git config user.name "Eclipse Keypop Bot"
          git add -A
          git commit --allow-empty -m "docs: update documentation from GitHub Actions job ${GITHUB_WORKFLOW}-${GITHUB_RUN_NUMBER}"
          git log --graph --abbrev-commit --date=relative -n 5
          git push origin HEAD:gh-pages